# Generated by Django 5.0.7 on 2024-07-25 12:24

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_doctor_phone_num_patient_symptoms"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Bed",
            new_name="amburance",
        ),
        migrations.RenameField(
            model_name="amburance",
            old_name="bed_number",
            new_name="amburance_number",
        ),
        migrations.RenameField(
            model_name="patient",
            old_name="bed_num",
            new_name="amburance_num",
        ),
        migrations.AddField(
            model_name="patient",
            name="Blood_pressure",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="Blood_type_and_Rh_factor",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="Body_Mass_Index",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="Current_gestational_age",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="Details_of_previous_deliveries",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="Diet_and_nutrition",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("Proteins", "Proteins"),
                    ("Carbohydrates", "Carbohydrates"),
                    ("Fats", "Fats"),
                    ("Vitamins and Minerals", "Vitamins and Minerals"),
                ],
                max_length=49,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="Exercise_routine",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("Normal exercises", "Normal exercises"),
                    ("not enough exercises", "not enough exercises"),
                    ("rarely do exercises", "rarely do exercises"),
                ],
                max_length=57,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="Heart_rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="Last_menstrual_period",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="Temperature",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="Weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="height",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="personal_behavious",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("Smoking", "Smoking"),
                    ("alcohol_drinking", "alcohol_drinking"),
                    ("drug_use", "drug_use"),
                ],
                max_length=33,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="prior_ailments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="symptoms",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("Fever", "Fever"),
                    ("vomiting", "vomiting"),
                    (" fatigue", " fatigue"),
                    ("Heartburn", "Heartburn"),
                    ("nausea", "nausea"),
                    ("Missed Periods", "Missed Periods"),
                    ("Swollen Breasts", "Swollen Breasts"),
                    ("Food Cravings", "Food Cravings"),
                    ("Mood Swings", "Mood Swings"),
                    ("Loss of taste or smell", "Loss of taste or smell"),
                ],
                max_length=120,
                null=True,
            ),
        ),
    ]
