# Generated by Django 5.0.7 on 2024-07-25 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_rename_bed_amburance_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="amburance",
            new_name="Ambulance",
        ),
        migrations.RenameField(
            model_name="ambulance",
            old_name="amburance_number",
            new_name="ambulance_number",
        ),
    ]
