# Generated by Django 5.0.7 on 2024-07-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_rename_amburance_ambulance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="delivered",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="operated",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
