# Generated by Django 5.0.7 on 2024-07-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_patient_delivered_patient_operated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="address",
            field=models.CharField(max_length=200),
        ),
    ]
