# Generated by Django 5.0.7 on 2024-07-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_patient_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="Details_of_previous_deliveries",
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name="patient",
            name="address",
            field=models.CharField(max_length=50),
        ),
    ]
