# Generated by Django 5.0.7 on 2024-07-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_patient_details_of_previous_deliveries_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result", models.PositiveIntegerField()),
            ],
        ),
    ]
