# Generated by Django 5.0.7 on 2024-07-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
