# Generated by Django 5.0.7 on 2024-07-27 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_patient_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="message",
        ),
    ]
