# Generated by Django 5.0.7 on 2024-09-09 08:40

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_remove_patient_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="symptoms",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("Fever", "Fever"),
                    ("vomiting", "vomiting"),
                    (" fatigue", " fatigue"),
                    ("Heartburn", "Heartburn"),
                    ("nausea", "nausea"),
                    ("Missed Periods", "Missed Periods"),
                    ("Swollen Breasts", "Swollen Breasts"),
                    ("Food Cravings", "Food Cravings"),
                    ("Mood Swings", "Mood Swings"),
                    ("Loss of taste or smell", "Loss of taste or smell"),
                    ("Heartburn", "Heartburn"),
                ],
                max_length=130,
                null=True,
            ),
        ),
    ]
