# Generated by Django 5.0.7 on 2024-09-09 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_alter_patient_symptoms"),
    ]

    operations = [
        migrations.CreateModel(
            name="BED",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bed_number", models.CharField(max_length=50)),
                ("occupied", models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name="patient",
            name="bed_num",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="main.bed"
            ),
        ),
    ]
