# Generated by Django 5.0.7 on 2024-07-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photos",
            field=models.ImageField(blank=True, null=True, upload_to="photos"),
        ),
    ]
